### ISSUE TITLE
\Data doesn't contain 'data.json' to start rendering the contents

### ISSUE THREAD

**Issue by vivekvit** [udacimak/udacimak#10]
![download dand](https://user-images.githubusercontent.com/45172004/48710691-2f8a2200-ec2f-11e8-9634-a423a412f498.PNG)
![folder dand](https://user-images.githubusercontent.com/45172004/48710795-7d068f00-ec2f-11e8-820e-2c55085e52af.PNG)

I'm unable to start rendering of JSON files - everytime it show these 2 errors - either the path doesn't exist or it is unable to find the file in it.

Is it something wrong I'm doing while entering the path

**Comment by udacimak** [comment]
Hi @vivekvit 

This is not an issue. It's just how we need to escape white space characters.
When using Windows, you need to wrap the path that contains space characters with double-quotes. For example:

```shell
C>\Users\320008059>udacimak render "_json\Data Analyst Nanodegree v7.0.0"
```

**Comment by mikeattara** [comment]
I am still facing the same issue. What can I do to rerender?

**Comment by mikeattara** [comment]
I am still facing the same issue. What can I do to re-render?

**Comment by udacimak** [comment]
@mikeattara please include enough information and log so I can help.

**Comment by mikeattara** [comment]
I have realized that the `-t` is necessary for it to be able to rerender. I wish to suggest making it require than optional. That will solve this issue IMO

**Comment by udacimak** [comment]
Hi @mikeattara 
`-t` is designed to be optional so that we can point the working directory of the terminal to the location where we want the rendered content to be. If the command fails you may want to check where's the working directory of the terminal is then `cd` (change directory) to the right place.

**Comment by mikeattara** [comment]
When I left out the `-t` flag, It was rendering to the same folder, hence causing the problem. Maybe you may consider setting the `-t` flag to `./Udacity` by default

**Comment by udacimak** [comment]
@mikeattara 
I think that's because the working dir of your terminal is the same location where the downloaded folder is located, hence the error. Udacimak requires downloaded content to be rendered in a different location. See more [here](https://github.com/udacimak/udacimak/blob/master/README.MD#important-render-directory-note)

**Comment by mikeattara** [comment]
Thanks
