### ISSUE TITLE
Broken LateX tables after rendering

### ISSUE THREAD

**Issue by alfredsasko** [udacimak/udacimak#108]
**Describe the bug**
The tables which are originally formatted in Latex using "|--|" notation are broken after rendering. See image.

**To Reproduce**
1. Install nvm-windows
2. Install udacimak v1.4.5 (to have video quality 720pxls)
3. Download and render nd025 (dsnd)

**Expected behavior**
Rendered successfully, need to check content (see screen-shot)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Node version: v13.12.0
 - npm version: 6.4.14
 - Udacimak Version: v1.4.5.
 - Browser:  Chrome

**Course Information**
 - Nanodegree or Course name: [Data Scientist Nanodegree]
 - Version: ...
 - Locale: en-us

**Additional context**
![broken_latex_tables](https://user-images.githubusercontent.com/44699562/78454548-ece8ae80-7698-11ea-8a5d-eee208394ada.png)

**Comment by udacimak** [comment]
Thanks @alfredsasko 
This is Markdown code, not LateX.

The issue is due to wrong Markdown formatting written by Udacity. The second line should be this instead:

```
|---|---|---|
```

I'm not sure how Udacity's Markdown renderer still renders the wrong syntax.
To correct the presentation of the table, you can go directly into the relevant `data.json` file and fix the syntax then run the `render` command again.
