### ISSUE TITLE
Udacimak stops on render of lesson from self driving car nanodegree

### ISSUE THREAD

**Issue by faultfactory** [udacimak/udacimak#2]
Udacimak version 0.10.3

Began render and it stopped at this same location. I ctrl-c'd to stop it and re-ran the render command. It stopped at the same location. No error is thrown and the udacimak.error and udacimak.exceptions log files are empty. The info mirrors the terminal output and ends at the following: 

```
2018-11-04T16:20:38.462Z [info]: Completed rendering lesson file SCDND//Self-Driving Car Engineer v1.0.0/Part 01-Module 03-Lesson 01_Introduction to Neural Networks/08. Classification Problems 1.html
2018-11-04T16:20:38.462Z [info]: ----------------------------------------
```

Is there a verbose flag that we can use to provide more info? 
Should I (can I?) post the .json file it is parsing from the initial download?

**Comment by udacimak** [comment]
Could you please email the `data.json` files to udacimak@tutanota.com ?

I will try to have a look later. I have rendered this ND successfully before though. Need to see if anything wrong in your ND version.

**Comment by udacimak** [comment]
I rendered the lesson and it works fine on Windows and MacOS.
I will set up a Ubuntu VM later to try to test the CLI on it so let's see if it's an issue on Ubuntu. Fingers crossed!

**Comment by udacimak** [comment]
@faultfactory 
I set up a [Ubuntu subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on Windows 10 to test it. But I was able to complete the render process for the lesson without errors:

```
etc....

2018-11-05T00:09:14.133Z [info]: Completed rendering lesson file /mnt/d/_udacidown/test/Lesson 01_Test/41. Create Your Own NN.html
2018-11-05T00:09:14.140Z [info]: ----------------------------------------
2018-11-05T00:09:17.071Z [info]:
Downloading video 42. Conclusion-m8xslYUBXYo.mp4:
 ████████████████████████████████████████ 100% | ETA: 1s | 1501978/1501978
2018-11-05T00:09:17.354Z [info]: Downloading subtitles for 42. Conclusion-m8xslYUBXYo.mp4
2018-11-05T00:09:21.281Z [info]: Downloaded subtitles for 42. Conclusion-m8xslYUBXYo.mp4
2018-11-05T00:09:21.290Z [info]: Completed rendering lesson file /mnt/d/_udacidown/test/Lesson 01_Test/42. Summary.html
2018-11-05T00:09:21.291Z [info]: ----------------------------------------
2018-11-05T00:09:21.293Z [info]: Completed parsing and creating local content for test
```

There are no errors thrown so I'm not sure why. But I think that it may be an `youtube-dl` issue that's causing your terminal to hang.
Could you try installing [`youtube-dl`](https://rg3.github.io/youtube-dl/) and use it to download the video `46PywnGa_cQ` on your end to see if it's successful? Please run `youtube-dl` with `--verbose` tag so that it logs error if any. Eg:

```
youtube-dl --verbose "https://www.youtube.com/watch?v=46PywnGa_cQ"
```

**Comment by udacimak** [comment]
@faultfactory 

I think it does sense that we should have `--verbose` param option to allow logging debug information.
I've added `-v`/`--verbose` tag for `render` and `renderdir` command options. It will make `youtube-dl` log the verbose messages. Please run `npm update -g udacimak` to get the latest `0.10.4` version.

Could you run `render` with `--verbose` parameter and check the debug message. Please post them here so that we can see if we can debug it.

FYI, here's what it shows on my end for your reference:

```
2018-11-05T08:18:02.184Z [info]: ----------------------------------------

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--dump-json', '--format=best', '--verbose', 'http://www.youtube.com/watch?v=UIycORUrPww']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}

2018-11-05T08:18:06.167Z [info]:
Downloading video 03. ND013 01 L Intro To Neural Networks-UIycORUrPww.mp4:
 ████████████████████████████████████████ 100% | ETA: 1s | 9972716/9972716
2018-11-05T08:18:07.878Z [info]: Downloading subtitles for 03. ND013 01 L Intro To Neural Networks-UIycORUrPww.mp4
2018-11-05T08:18:12.769Z [info]: Downloaded subtitles for 03. ND013 01 L Intro To Neural Networks-UIycORUrPww.mp4
2018-11-05T08:18:12.781Z [info]: Completed rendering lesson file D:\_udacidown/test/Lesson 01_Test/03. Starting Machine Learning.html
```

**Comment by faultfactory** [comment]
The problem was not reproducible this time for the same content.  It hung for about 30 seconds and then continued. I am going to continue letting it render until it stops or i need to leave. I will post the output when I get back.

**Comment by faultfactory** [comment]
As requested

'''

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--dump-json', u'--format=best', u'--verbose', u'http://www.youtube.com/watch?v=46PywnGa_cQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
'''

**Comment by faultfactory** [comment]
Brute force approach of ctrl+c and restarting worked. Unclear as to why.

**Comment by udacimak** [comment]
@faultfactory 

Thanks. Your _debug log_ looks fine 👍 
I've set up a _Ubuntu 18_ machine via _Windows Hyper V_ and have been rendering without problems.

I suspect that you could be experiencing network issues. I think this is not a `youtube-dl` or `udacimak` issue.

I can keep this issue _opened_ until you finish rendering SDCND. Please update if you see any hints of errors, or if you have finished rendering successfully!

------------------

__PS.__ I have set up a Docker image. If you're familiar with Docker, you can use it instead of the VM for convience.
- https://github.com/udacimak/udacimak#use-udacimak-via-docker-container

**Comment by faultfactory** [comment]
@udacimak 

I've had a few 'socket hang up' errors and various other small hiccups that I believe are the result of network traffic issues. I can usually get it to work via more brute force retrys.  I'm currently on Part 03 of nd013 and hopefully it continues successfully.  

I believe whatever I'm fighting is a result of things outside the control of udacimak's code. That said, since a simply re-starting the render will usually get this to work, perhaps it's worth adding a timeout and re-try function if the render stops or throws an error? Maybe it repeats the attempt every x seconds? 

I realize you have a feedback sample size of 1 user.  To make sure this would make sense, I ran this on Ubuntu 16.04 (base install) and Ubuntu 18.04 in the Hyper-V VM. I bumped into separate issues on both and restarting until it ran worked fine. The info file will contain the errors so when I complete the render, I will send it to you.

**Comment by faultfactory** [comment]
Render completed. I've attached the exceptions file.  The info file is excessively large due to the multiple restarts. 


[udacimak.exceptions.log](https://github.com/udacimak/udacimak/files/2554168/udacimak.exceptions.log)

**Comment by udacimak** [comment]
Thanks @faultfactory 

I will look into this further to see how Udacimak can improve UX for cases like this. Will keep this issue opened til further updates.

**Comment by rgekhman** [comment]
Just a tip: 
I'm on Win 10. My rendering of video content would stop 4-5 times before fully completed. And solution for it was to refresh Udacity session, and re-enter _jwt token (i.e. run command "udacimak settoken <token>") then re-run "udacimak render ... " command.
