### ISSUE TITLE
You are a SUPERHERO! (Actually this is not an issue)

### ISSUE THREAD

**Issue by qiweiyang2018** [udacimak/udacimak#30]
Hello, 

You save my day! Before I had to manually save every single page all by myself, which makes me want to kill myself. 

I am C++ user and do not know Javascript much, however from your project I start realizing how powerful JS is in the domain of the web. I'd like to learn JS from your source codes. Could you shed light in how to read/learn your codes?

Thanks a lot!

**Comment by udacimak** [comment]
Thanks @qiweiyang2018 😄 

Taking Udacity front end degree would definitely an option. I guess if you read the code you can read from top file down, it'll be easy to understand. Notes the packages I use in the `webpack` files since I use quite some libraries.

Have fun and happy to hear that you find the CLI helpful!
