### ISSUE TITLE
Student quiz responses

### ISSUE THREAD

**Issue by cfdesign** [udacimak/udacimak#6]
Hello, firstly BIG, HUGE THANKS!

I am a Front End Developer ND grad. I have noticed within the javascript coding quizzes, my saved answers are not being displayed. I like to reflect on what my responses were for the quiz, so this is a suggestion for enhancement.

Digging around in a .json I can see that a quiz page object contains the data I am seeking. 
Objects with quiz data seem to include a key of: 
`"semantic_type": "QuizAtom",`

and with the key:
`"user_state":`

within which is another object key-value pair:
`{ "unstructured": "// student-quiz-response"}`

Hopefully within a future release there might be a way to include this student data in the renders?

Once again, super job!

**Comment by udacimak** [comment]
Thanks @cfdesign !

I'm very happy to hear you find the app helpful!

Just to recap quickly, there are 6 types of quizzes in Udacity API data.
Almost all quiz types already have Udacity's solution provided, except for `ProgrammingQuestion`, which belongs to `QuizAtom`. For quiz types that already contain Udacity's solutions, I think it's agreeable that we don't need getting user's response from `user_state`.

So `ProgrammingQuestion` is the only quiz type that usually doesn't have Udacity's solution, but contains `user_state`, which has the user's response to the quiz.
Because this is not consistent with the other quiz types, I think I will add an extra command option that will force the `render` command to include user's code answer for `ProgrammingQuestion`. So this is will not be a default behaviour of `render`, but if you want, you will be able to add an option to reveal the user's code in the renders.

I'm looking at doing this over the weekend and can release a minor version. Stay tuned!

**Comment by udacimak** [comment]
I have added this optional feature in `v1.2.0` (just released). If you use the optional parameter `--userquizanswer`, it will show the user's code answer:

![2018-11-15 20_47_32-quiz atom example](https://user-images.githubusercontent.com/44603004/48544465-c006f080-e917-11e8-81e0-34b520e8c97e.png)

Enjoy!

**Comment by cfdesign** [comment]
How dare you make this enhancement all before I can get the opportunity to get a reply in! 😂 
You are an absolute legend! Yesterday I took some time to try and dissect all the intricate pieces of the app you have made, it's truly amazing! You certainly are very inspirational, I can only dream of being capable of such a large scale project.

Reading your initial response re: the additional insight into the quiz types that are possible, was very interesting, thank you. I fully agree with your thinking that, where possible, supplied (Udacity) solutions should be default. 

It had come to my attention that the desire to reveal the user data for the programming quiz, may not always be best/correct. In my case however, I never moved away from a quiz, until it was marked up as correctly satisfying conditions of the task. I respect your consideration for including a _User Note_ there too!

Well this enhancement came almost instantly, which is completely amazing! You'll have to find something else to do at the weekend now. 

Much respect & thanks!
