### ISSUE TITLE
Install giving me an error

### ISSUE THREAD

**Issue by GeeR13** [udacimak/udacimak#96]
when running “npm install -g udacimak” to install udacimak I get the error below. 

![image](https://user-images.githubusercontent.com/37272511/77885901-c05a1000-721c-11ea-87d9-0768b0d21be0.png)

**Comment by udacimak** [comment]
Please detail the issue as in the original template when you open an issue

**Comment by harikrishna1999** [comment]
after installing
node.js
while running npm install -g udacimak
im getting this error
![image](https://user-images.githubusercontent.com/33798664/77923406-0b792f00-72c0-11ea-8b7a-80a69f597318.png)

**Comment by PaulinoRBJ** [comment]
I'm getting this error too!

**Comment by 1871vinayak** [comment]
@GeeR13 
Yeah there's an update `v1.6.0` . 
You can follow the steps to get it working for you.
- Uninstall
 `npm uninstall -g udacimak`
- Install
 `npm install -g udacimak`

Alternate method is: [**This will surely solve this issue**]
-  Uninstall udacimak if you have installed it globally:
`npm uninstall -g udacimak`
- Install Node and npm. Installing via nvm is highly recommended:
    - ` https://github.com/creationix/nvm`
    - ` https://github.com/coreybutler/nvm-windows`
- Install required dependencies:
   - ` npm install`
   - `npm run-script build`
- Create symlink for the package folder so that you can run udacimak command:
    `npm link`

   - Run `udacimak --help` and make sure that it works

**Comment by yumengdong** [comment]
I had the same issue. You can used yarn to install:
```
npm i -g yarn
yarn global add udacimak
```

**Comment by GeeR13** [comment]
> I had the same issue. You can used yarn to install:
> 
> ```
> npm i -g yarn
> yarn global add udacimak
> ```

this worked, i ran npm list udacimak and it came back with 
/Users/GeeR13
└── (empty)
I then ran udacimak --version and i got 
-bash: udacimak: command not found

any ideas?
